name: CI for OrderProcessing

on:
  push:
    branches: [ main, development, feature/* ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore OrderProcessingSolution.sln
      continue-on-error: false

    - name: Build
      run: dotnet build OrderProcessingSolution.sln --no-restore --configuration Release
      continue-on-error: false

    - name: Run tests
      run: dotnet test OrderProcessingSolution.sln --no-build --verbosity normal
      continue-on-error: false