name: CI - Build and Test

on:
  push:
    branches: [main, development, feature/*] # Runs on push to these branches
  pull_request:
    branches: [main, development]  # Runs on PRs to these branches

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Match your project version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test OrderProcessing.Tests/OrderProcessing.Tests.csproj --no-build --configuration Release --logger trx --results-directory TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: TestResults
          path: TestResults/
